### ISSUE TITLE
Only top message is shown, exception message with helpful information is not visible

### ISSUE THREAD

**Issue by realnickivanov** [airbrake/sharpbrake#120]
I have AirBrake integrated with NLog. When I run code similar to the provided below and then go to AirBrake website to see the logged error, I only see the top message ("foo"). I would also like to see exception.Message ("bar") and exception.InnerException.Message ("baz"), but they are not there.

```
var message = "foo";
var innerMessage = "bar";
var innerInnerMessage = "baz";
try
{
    try
    {
        throw new Exception(innerInnerMessage);
    }
    catch(Exception ex)
    {
        throw new Exception(innerMessage, ex);
    }
}
catch (Exception exception)
{
    //NLOG
    _logger.Error(exception, message);
}
```

**Comment by rbalabukh** [comment]
@realnickivanov, a message provided to log method is replacing first exception message. Messages from inner exceptions you can find in Backtrace section of error log.
