### ISSUE TITLE
How to use airbrake with asp.net webform website project type?

### ISSUE THREAD

**Issue by jubbabo** [airbrake/sharpbrake#127]
We have a web application developed under .NET framework 4.6.1. It is not MVC. It's webform and it's website project type, not web application project type. 

Can we integrate Airbrake with our application?

**Comment by rbalabukh** [comment]
Yes, you can add HTTP Module
[https://github.com/airbrake/sharpbrake#aspnet-http-module](url)
or you can call directly from your try/catch block
[https://github.com/airbrake/sharpbrake#basic-example](url)

**Comment by jubbabo** [comment]
Thank you for your reply, rbalabukh. I will try. Any further question, I will post again.
