### ISSUE TITLE
SharpBrake and my .NET Framework 2.0 project

### ISSUE THREAD

**Issue by valbb66** [airbrake/sharpbrake#15]
Hi, I am trying to install SharpBrake through NuGet and Visual Studio 10. My web application targets .NET Framework 2.0. SharpBrake targets .NET Framework 3.5. I could not install SharpBrake. Is there anything I can do to make it work for my project. Thank you for your time, Valentina

**Comment by aholovko** [comment]
Hi, Valentina. Thanks for your interest in Sharpbrake. We have released a brand new version of our notifier with a lot of new features recently. Sadly, there is no support for .NET Framework 2.0 as it's very-very old as for now. We suggest you upgrade your app to at least .NET Framework 4.5 but if you are still interested in support for .NET Framework 2.0 plz let me know, and we can work together on an optimal solution. I am closing this issue, but feel free to open a new one if you want to have further discussion.
