### ISSUE TITLE
Read settings from environment variables

### ISSUE THREAD

**Issue by Iristyle** [airbrake/sharpbrake#22]
Presently, config settings are being read in `AirbrakeConfiguration.cs` like this.  When deploying (i.e. to Mono, with Capistrano, using Foreman to export a Procfile to an Upstart script), it's preferable to export environment variables.

``` csharp
ApiKey = ConfigurationManager.AppSettings["Airbrake.ApiKey"];
EnvironmentName = ConfigurationManager.AppSettings["Airbrake.Environment"];
ServerUri = ConfigurationManager.AppSettings["Airbrake.ServerUri"]
  ?? "https://api.airbrake.io/notifier_api/v2/notices";
```

This could easily be rewritten to favor env variables first for each like so:

``` csharp
Environment.GetEnvironmentVariable("Airbrake.ApiKey")  ?? 
  [ConfigurationManager.AppSettings["Airbrake.ApiKey"]
```

Of course, it would also be better to use conventions for these variable names like
- AIRBRAKE_API_KEY
- AIRBRAKE_ENVIRONMENT
- AIRBRAKE_SERVER_URI

Thoughts?

**Comment by aholovko** [comment]
With new Sharpbrake you are in full control on how config values are set. You can use the next code to initialize config options from environment variables:
```csharp
var airbrake = new AirbrakeNotifier(new AirbrakeConfig
{
    ProjectId = Environment.GetEnvironmentVariable("AIRBRAKE_PROJECT_ID"),
    ProjectKey = Environment.GetEnvironmentVariable("AIRBRAKE_PROJECT_KEY")
});
```
I am closing this issue. Please feel free to open a new one if further discussion is needed.
