### ISSUE TITLE
Incorrect line numbers in Airbrake backtrace

### ISSUE THREAD

**Issue by cvachon-akivo** [airbrake/sharpbrake#29]
When an exception occurs, the backtrace in Airbrake gives me incorrect line numbers

Here are some examples I got from the backtrace of one of my exceptions:

`Synchronisation:1165 in SynchroniserProduits` (Correct line number is 120)
`Synchronisation:189 in SynchroniserInventaire` (Correct line number is 63)
`Synchro:125 in ProcessRequest` (Correct line number is 24)

There does not seem to be a pattern to the line number differences.

Hypothesis: could the faulty line numbers be from the Common Intermediate Language (CIL) code?

**Comment by hiblen** [comment]
I am experiencing this same problem - we are using NLog.Airbrake (which uses SharpBrake) and the line numbers reported in Airbrake are regularly way off.  I normally end up needing to log to two sources so I can use Airbrakes fantastic interface AND get the correct line numbers.

Please let me know if you would like any more info.

**Comment by aholovko** [comment]
Please give it another chance with a new version of our notifier. A lot of [new features](https://github.com/airbrake/sharpbrake#key-features) and bug fixes have been added, and we hope that the problem with incorrect line numbers is fixed as well. But if it's still there, please create new issue with some details on your app/configuration (e.g. you are using some inline optimization techniques, code obfuscating or code fragments are generated dynamically, etc.) and we will try to fix it as soon as possible.
