### ISSUE TITLE
Disable SharpBrake in local development environment

### ISSUE THREAD

**Issue by denisahearn** [airbrake/sharpbrake#30]
I don't see a way to configure SharpBrake to not notify AirBrake when running in local development mode.  The best I found to do is define an empty Airbrake.ApiKey in App.config, which prevents Airbrake from being notified, but results in the following error message getting logged:

015/09/30 10:51:39:646 [FATAL] SharpBrake.AirbrakeClient - No 'Airbrake.ApiKey' found. Please define one in AppSettings.

It would be nice if I could do something like this in my App.config, which would instruct SharpBrake to silently do nothing (or maybe log a Debug message saying that its disabled):

```
<add key="SharpBrake.Enabled" value="False" />  <!-- Default is True -->
```

**Comment by aholovko** [comment]
Notifying can be disabled in certain environments using a combination of [Environment](https://github.com/airbrake/sharpbrake#environment) and [IgnoreEnvironments](https://github.com/airbrake/sharpbrake#ignoreenvironments) properties. I am closing this issue but please let us know if doesn't work for you. Thanks.
