### ISSUE TITLE
Airbrake.ServerUri in appSettings

### ISSUE THREAD

**Issue by claytonfbell** [airbrake/sharpbrake#32]
It looks like `exception.SendToAirbrake()` does **not** work when this line is in the app.config.

``` xml
<appSettings>
...
<add key="Airbrake.ServerUri" value="http://api.airbrake.io" />
</appSettings>
```

I got this from the install instructions when I created the new airbrake project.

Works fine when removed though.

**Comment by greenlynx** [comment]
I can confirm this - spent ages trying to figure this out!

**Comment by aholovko** [comment]
Recently we have released a new version of notifier that shouldn't have mentioned problem anymore. All new instructions are in the [README](https://github.com/airbrake/sharpbrake/blob/master/README.md) file. I am closing this issue, but if you discover any new problem, please open an issue so we can work together on it. It's nice to be in touch with you again.
