### ISSUE TITLE
When using e.SendToAirBrake() I get an error 

### ISSUE THREAD

**Issue by BasicsCoding** [airbrake/sharpbrake#34]
An unhandled exception of type 'System.TypeLoadException' occurred in SharpBrake.dll

Additional information: Could not load type 'Common.Logging.FormatMessageHandler' from assembly 'Common.Logging, Version=1.2.0.0, Culture=neutral, PublicKeyToken=af08829b84f0328e'.

on: 

   catch (Exception e)
            {
                e.SendToAirbrake();
            }

**Comment by jchristn** [comment]
You may need to do a NuGet update on that library.  I had the same issue.

**Comment by aholovko** [comment]
New notifier shouldn't have that problem anymore. You can get it easily from the [NuGet](https://github.com/airbrake/sharpbrake#nuget) repo.
