### ISSUE TITLE
A few issues encountered

### ISSUE THREAD

**Issue by stevenx402** [airbrake/sharpbrake#39]
I've just started implementing AirBrake into one of our projects as a trial, however I'm having a few issues - hopefully someone here might be able to answer them (though I notice this library hasn't been updated in 2 years...)

1. Our app has request validation enabled, however when a "A potentially dangerous Request.Form value was detected from the client" is triggered, AirBrake is itself throwing an exception when trying to process the Form data.  This means that we have to Try Catch the SendToAirBrake itself.

2. We are trialing this just now, so it has to run along side our existing error notification system, however when we call the exception.SendToAirBrake function, this seems to be causing the thread to lock and the request never ends, leaving the user hanging indefinitely - this is requiring us to run the SendToAirBrake command in a separate Task in order to prevent locking, which seems like it should be unnecessary (this fix also only seems to work locally in dev, when live we are still seeing the request 'hanging' when an error occurs).     Looks like it might be issue with an Async function being called in a non-async manner.

3. All errors logged in the dashboard are coming through with the URL of http://www.example.com/ rather than the actual URL being requested.

Any feedback on these issues would be appreciated.

**Comment by aholovko** [comment]
These issues should be resolved in our new notifier. Among other [features](https://github.com/airbrake/sharpbrake#key-features) it's totally asynchronous, so your code shouldn't become slower or be blocked. Please keep us in touch on your integration and let us know if any new issues happen. Thanks.
