### ISSUE TITLE
Fix "notifier" payload inside Context

### ISSUE THREAD

**Issue by kyrylo** [airbrake/sharpbrake#44]
We send language information (for example "C#/NETCORE"), however we don't send "notifier" payload.

Example payload:

```
"notifier": {
    "name": "Sharpbrake",
    "url": "https://github.com/airbrake/sharpbrake"
    "version": "3.0.1"
  },
```

It *seems* like [we are supposed to send it](https://github.com/airbrake/sharpbrake/blob/master/src/Sharpbrake.Client/Model/NotifierInfo.cs) but it appears to be broken. The payload I see in the dashboard is this:

```
{
  "hostname": "",
  "language": "C#/NETCORE",
  "os": "Microsoft Windows 10.0.14393 ",
  "remoteAddr": "[redacted ;)]"
}
```

**Comment by aholovko** [comment]
Give me 30 min to check that.

**Comment by kyrylo** [comment]
Fixed by https://github.com/airbrake/sharpbrake/pull/46.
