### ISSUE TITLE
Implement an integration with nLog

### ISSUE THREAD

**Issue by kyrylo** [airbrake/sharpbrake#50]
A customer requested an integration with https://github.com/NLog/NLog
> NLog - Advanced .NET, NETSTANDARD, Silverlight and Xamarin Logging

In terms of its interface and features, it should be similar to our existing integration with glog for Go: https://github.com/airbrake/glog

**Comment by aholovko** [comment]
Implemented in PR #65, released in [v4.1.0](https://github.com/airbrake/sharpbrake/releases/tag/v4.1.0)

**Comment by kyrylo** [comment]
Nice one 👍
