### ISSUE TITLE
.Net 4.5 project gets nugget error

### ISSUE THREAD

**Issue by sqlgrease** [airbrake/sharpbrake#64]
I get the following error when I try adding the nuget package to a .net 4.5 project:

Install failed. Rolling back...
Install-Package : Could not install package 'Sharpbrake.Client 4.0.1'. You are trying to install this package into a project that 
targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with 
that framework. For more information, contact the package author.

**Comment by aholovko** [comment]
Hi @sqlgrease, the current library supports .NET Framework version 4.5.2 and above. For .NET 4.5 you need to use https://github.com/airbrake/sharpbrake-net35:
```
PM> Install-Package Sharpbrake.Client -Version 3.2.1
```
or
```
PM> Install-Package Sharpbrake.Http.Module -Version 1.2.1
```
Please, let me know if you need further assistance. Thank you.

**Comment by aholovko** [comment]
Let us know if you still have the issues with support for .NET 4.5. I am closing this one but feel free to re-open it if you need any further assistance.
