### ISSUE TITLE
Problem with Sharpbrake.Cliente 3.1.1, .NET console application. 

### ISSUE THREAD

**Issue by nicokras** [airbrake/sharpbrake#70]
Hi, Cannot make it work from .NET . We have installe de Sharpbrake.Client v3.1.1 (as we need it to make it work on .NET 3.5)

_AirbrakeNotifier = new AirbrakeNotifier(_AirbrakeHelper.config);

_AirbrakeNotifier.NotifyCompleted += (sender, eventArgs) =>
{
if (eventArgs.Error != null)
Console.WriteLine(eventArgs.Error.Message);
else if (eventArgs.Result != null)
{
var response = eventArgs.Result;
Console.WriteLine("Status: {0}, Id: {1}, Url: {2}", response.Status, response.Id, response.Url);
}
};

_AirbrakeNotifier.NotifyAsync(new Exception(_AirbrakeHelper.projectName));

Thanks

**Comment by aholovko** [comment]
Hi @nicokras,

Most probably, the program exits before the notifier gets a chance to do its job (and thus all child threads are killed). Could you, please, try to add some kind of thread waiting, like this one:

```csharp
private static readonly EventWaitHandle waitHandle = new AutoResetEvent(false);
```

```csharp
notifier.NotifyCompleted += (sender, eventArgs) =>
{
    if (eventArgs.Error != null)
        Console.WriteLine(eventArgs.Error.Message);
    else if (eventArgs.Result != null)
    {
        var response = eventArgs.Result;
        Console.WriteLine("Status: {0}, Id: {1}, Url: {2}", response.Status, response.Id, response.Url);
    }
    waitHandle.Set(); // <--- SIGNAL THAT WE ARE DONE
};

notifier.NotifyAsync(new Exception("Oops"));
waitHandle.WaitOne(5000); // <--- WAIT FOR SIGNAL BUT NO MORE THAN 5 SEC
```

Usually in web apps this is not a problem because at least one thread is alive that is not always true for the console app. Please, let me know if this works for you. Thanks.

**Comment by nicokras** [comment]
Great! It was a matter of time then.

Thanks for your help-

**Comment by aholovko** [comment]
I'm glad that problem was solved. Let me know if anything else is needed.
