### ISSUE TITLE
Log4net logging does not send errors to airbrake

### ISSUE THREAD

**Issue by kentonbmax** [airbrake/sharpbrake#77]
Please see the attached log4net appender configuration. Graylog gets errors just fine and airbrake works with angular just fine. I'm using a project type of .net. 

![airbrake_li](https://user-images.githubusercontent.com/15804484/32232655-e6b1047e-be2e-11e7-9823-2bf621d42b3a.jpg)

**Comment by aholovko** [comment]
Hi Kenton, what type of ASP.NET application are you using? Is it ASP.NET MVC or Core? And what is the version of .NET Framework in case if this is not .NET Core? Could you please also update the type from "Sharpbrake.Log4net.AirbrakeAppender, Sharpbrake.Log4net" to "Sharpbrake.Log4net.Web.AirbrakeAppender, Sharpbrake.Log4net.Web" so the configuration becomes:

```csharp
<appender name="Airbrake" type="Sharpbrake.Log4net.Web.AirbrakeAppender, Sharpbrake.Log4net.Web">
  <projectId value="..." />
  <projectKey value="..." />
  <layout type="log4net.Layout.PatternLayout">
    <conversionPattern value="%message%newline" />
  </layout>
</appender>
```

**Comment by kentonbmax** [comment]
just a plain jane 4.5.2 console app.

**Comment by aholovko** [comment]
Most probably the problem is in async nature of the Airbrake notifier - in the case of console app the main thread exits before the notifier gets a chance to send the message. Kenton, could you please add `Thread.Sleep` after the logging command, ex:

```csharp
XmlConfigurator.Configure(new FileInfo("log4net.config"));

try
{
    var number = 0;
    var result = 10 / number;
}
catch (Exception ex)
{
    log.Error("Oops", ex);
    Thread.Sleep(5000); // <---- wait for 5 sec
}
```
and let me know if it helps. If this is a case I will think on some optimal solution for such cases. Thank you for your help in making our product better.

**Comment by kentonbmax** [comment]
tried your suggestion. The logger.log() is called from a loop with a 3 sec
delay before calling the log function. which should allow me to test how
well aribrake handles concurrent errors. Still I get no errors in airbrake.

class AsyncLogger
    {
        private static readonly ILog _log =
LogManager.GetLogger(typeof(AsyncLogger));
        public async Task<bool> Log()
        {
            try
            {
                _log.Error("test");
                Thread.Sleep(5000)
                await Task.Delay(1000);
                Console.WriteLine("Logged");
            }
            catch (Exception ex)
            {
                _log.Error(ex);
                return false;
            }

            return true;
        }
    }

**Comment by aholovko** [comment]
Kenton, could you please show how you initialize the log4net? Is it done via configuration attribute, code like `BasicConfigurator.Configure()` or some other way? Thanks.

**Comment by aholovko** [comment]
We have added [tracing functionality](https://github.com/airbrake/sharpbrake#debugging-and-diagnostics) to our notifier that can help to investigate the reason why notice is not being sent. Kenton, please let us know if you still have that issue so we can work together and get more insights for your case. Thank you.
