### ISSUE TITLE
Can only transmit errors with exceptions

### ISSUE THREAD

**Issue by danzel** [airbrake/sharpbrake#79]
Maybe this is a limitation of airbrake, but something I ran in to while getting acquainted.
I've got the `Sharpbrake.Extensions.Logging` integration set up and working.

This will send something to airbrake:
```cs
try
{
	throw new Exception("My Exception");
}
catch (Exception e)
{
	_logger.LogError(e, "Something bad happened");
}
```

But this won't:
```cs
_logger.LogError("Something bad happened without an exception");
```

Is it possible to have the second one send an error?

**Comment by aholovko** [comment]
Hi @danzel, we just released version 5 of Sharpbrake with support for error messages. Please let me know if you need any assistance.
