### ISSUE TITLE
.NET Core 2.0 dependency possible issue

### ISSUE THREAD

**Issue by leandroalemao** [airbrake/sharpbrake#81]
* Sharpbrake.NLog version: 1.3.0
* .NET platform version: .NET Core 2

#### Description
Hi, 
Seems like Sharpbrake.NLog ([csproj](https://github.com/airbrake/sharpbrake/blob/master/src/Sharpbrake.NLog/Sharpbrake.NLog.csproj)) is locked to NLog 5.0.0-beta11 for .NET Core 2 apps.. and I think there'll be not version 5 of NLog for now.. https://github.com/NLog/NLog.Extensions.Logging/wiki/Getting-started-with-.NET-Core-2---Console-application which says like NLog 4.5.0-rc versions it's ok for Core 2 apps.

Can someone please have a look at this pls?

**Comment by aholovko** [comment]
Thanks @leandroalemao, I am looking into this issue.

**Comment by aholovko** [comment]
@leandroalemao We have released a [new version](https://www.nuget.org/packages/Sharpbrake.NLog/1.4.0) of our NLog integration that is dependent on NLog version 4.5.0-rc03 for netstandard2.0 projects. Please let us know if you discover any new issue. Thanks for your help in making our product better.
