### ISSUE TITLE
Error creating SSL/TLS Channel (Solved)

### ISSUE THREAD

**Issue by brainwipe** [airbrake/sharpbrake#95]
I don't think this is a bug with Sharpbrake but I received it while using Sharpbrake because it's the only part of my app that negotiates a stream. There's a solution and explanation at the bottom, provided for any others.

* Sharpbrake version: 5.0.1
* .NET platform version: 4.6.2

#### Airbrake config
Performed in web.config.

    <add key="Airbrake.Environment" value="developer" />
    <add key="Airbrake.ProjectId" value="<secret>" />
    <add key="Airbrake.ProjectKey" value="<secret>" />

#### Description
Running on a dev machine that uses IIS and self-signed certificates to run SSL locally. I use a mapped hostname of `localhost.com` in my hosts file.

When sending an exception to Airbrake, I get the following exception:

    System.Net.WebException
    The request was aborted: Could not create SSL/TLS secure channel.
     at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
     at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

The code I'm using to test Airbrake is an MVC service:

    public class TestErrorController : Controller
    {
        [HttpGet]
        public ActionResult Throw500()
        {
            var exception = new InvalidOperationException("Test Error Controller was called and this is a test 500 error exception");
            exception.SendToAirbrake();
            throw exception;
        }
    }

For this example, I use an extension method `SendToAirbrake()`. You don't need the SendToAirbrake() call as the Http Module nuget package will do that for you. However, to help debug this problem, I needed to use the extension method. It looks like this:

     public static class ExceptionExtensions
    {
        public static void SendToAirbrake(this Exception exception)
        {
            AirbrakeNotifier airbrakeNotifier = Singleton<IUnityContainer>.Instance.Resolve<AirbrakeNotifier>();
            
            var notice = airbrakeNotifier.BuildNotice(exception);
            var result = airbrakeNotifier.NotifyAsync(notice).Result;
        }

    }

The notifier is injected via Unity. Here's the configuration:

    private static void InitialiseLogger(IUnityContainer container)
    {
            var settings = ConfigurationManager.AppSettings.AllKeys
                                               .Where(key => key.StartsWith("Airbrake", StringComparison.OrdinalIgnoreCase))
                                               .ToDictionary(key => key, key => ConfigurationManager.AppSettings[key]);

            var config = AirbrakeConfig.Load(settings);
            var airbrake = new AirbrakeNotifier(config);
            container.RegisterInstance(airbrake);
    }

Which is called via a small chain of methods from global.asax.

#### Solution
The problem appears to be that .NET 4.6.2 does not [default to a security protocol](https://msdn.microsoft.com/en-us/library/system.net.servicepointmanager.securityprotocol(v=vs.110).aspx#Anchor_2). So, it will use whatever is listed on your machine. You can see that by putting this into Powershell:

    [Net.ServicePointManager]::SecurityProtocol

I have:

    Ssl3, Tls

SSL3 is vulnerable to the [POODLE attack](https://blog.mozilla.org/security/2014/10/14/the-poodle-attack-and-the-end-of-ssl-3-0/) so you need to tell .NET to use the stronger TLS protocols rather than insecure SSL3. Airbrake won't let you use SSL3 and rightly so.

Depending on which .NET version you're running, that will involve something different. For me, it was setting the `ServicePointManager.SecurityProtocol` in my global.asax startup. This forces my system to use TLS at least one of the TLS versions and not SSL3. It's not forwardly compatible, thus the comment.

    // TODO Remove on 4.7 infrastructure upgrade
    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls |
                                                   SecurityProtocolType.Tls11 | 
                                                   SecurityProtocolType.Tls12;

**Comment by aholovko** [comment]
Thank you Rob for all your valuable investigations. We will think on improving support of different security protocols within the notifier itself and your investigations should help here a lot.

**Comment by brainwipe** [comment]
You're welcome. I think this is a very-edge case and I'm only hitting it while I wait for an infrastructure upgrade to .NET 4.7.x. I wanted to share for others rather than an action for you. Hopefully Google has spidered it by now, so please do close this issue if you like.

**Comment by rbalabukh** [comment]
https://github.com/airbrake/sharpbrake/issues/106
