### ISSUE TITLE
Support X-Forwarded-For in Log4Net

### ISSUE THREAD

**Issue by kyrylo** [airbrake/sharpbrake#98]
A user reported a bug: Sharpbrake Log4Net doesn't respect X-Forwarded-For when the app is behind a proxy. The reported IP is the IP of the proxy server. That is, `context.remoteAddr` is the IP address of the reverse proxy server, and `context.userAddr` is non-existent.

**Comment by willseward** [comment]
@kyrylo Has there been any movement on this issue?

**Comment by kyrylo** [comment]
Fixed by #99.

@rbalabukh let's cut a release unless there are more features/bug fixes that you are currently working on.
